





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;
using Sitecore.Data.Items;


namespace DoctaCore.Project.Demo
{
    public partial interface IGlassBase
    {

        [SitecoreId]
        Guid Id { get; }

        [SitecoreItem]
        Item Item { get; }

        [SitecoreParent]
        Item Parent { get; }

        [SitecoreChildren]
        IEnumerable<Item> Children { get; }

        [SitecoreInfo(SitecoreInfoType.Language)]
        Language Language { get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

        [SitecoreInfo(SitecoreInfoType.Url)]
        string Url { get; }

        [SitecoreInfo(SitecoreInfoType.BaseTemplateIds)]
        IEnumerable<Guid> BaseTemplateIds { get; }

        [SitecoreInfo(SitecoreInfoType.TemplateId)]
        Guid ItemTemplateId { get; }

        bool InheritsTemplate(Guid templateGuid);

        bool InheritsTemplate(ID templateId);
    }

    public abstract partial class GlassBase : IGlassBase
    {

        [SitecoreId]
        public virtual Guid Id { get; private set;}

        [SitecoreItem]
        public virtual Item Item { get; private set; }

        [SitecoreParent]
        public virtual Item Parent { get; private set; }

        [SitecoreChildren]
        public virtual IEnumerable<Item> Children { get; private set; }

        [SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language { get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

        [SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }

        [SitecoreInfo(SitecoreInfoType.BaseTemplateIds)]
        public virtual IEnumerable<Guid> BaseTemplateIds { get; private set; }

        [SitecoreInfo(SitecoreInfoType.TemplateId)]
        public virtual Guid ItemTemplateId { get; private set; }

        /// <summary>
        /// Returns a bool indicating if the item inherits the given template
        /// </summary>
        /// <param name="templateGuid">Template Guid</param>
        /// <returns>True if the item is or inherits from a template</returns>
        public bool InheritsTemplate(Guid templateGuid)
        {
            return this.BaseTemplateIds.Contains(templateGuid) || this.ItemTemplateId.Equals(templateGuid);
        }

        /// <summary>
        /// Returns a bool indicating if the item inherits the given template
        /// </summary>
        /// <param name="templateId">Template ID</param>
        /// <returns>True if the item is or inherits from a template</returns>
        public bool InheritsTemplate(ID templateId)
        {
            return this.InheritsTemplate(templateId.Guid);
        }
    }
}
namespace DoctaCore.Project.Demo
{


  /// <summary>
  /// IArticle Interface
  /// <para></para>
  /// <para>Path: /sitecore/templates/Project/Demo/Page Types/Article</para> 
  /// <para>ID: 0e7add70-1756-45b7-b0a3-95af072fc68f</para>  
  /// </summary>
  [SitecoreType(TemplateId=IArticleConstants.TemplateIdString )] //, Cachable = true
  public partial interface IArticle : IGlassBase , global::DoctaCore.Project.Demo.IBase_Page
  {
                /// <summary>
          /// The Introduction field.
          /// <para></para>
          /// <para>Field Type: Rich Text</para>    
          /// <para>Field ID: 66f51940-5f6f-404b-8dd9-81dee8e6bb07</para>
          /// <para>Custom Data: </para>
          /// </summary>
          [SitecoreField(IArticleConstants.IntroductionFieldName)]
          string Introduction  {get; set;}
      
                /// <summary>
          /// The Main Content field.
          /// <para></para>
          /// <para>Field Type: Rich Text</para>    
          /// <para>Field ID: 07b7ab11-8edf-4edb-a1cc-7c981b2dee04</para>
          /// <para>Custom Data: </para>
          /// </summary>
          [SitecoreField(IArticleConstants.Main_ContentFieldName)]
          string Main_Content  {get; set;}
      
                /// <summary>
          /// The Title field.
          /// <para></para>
          /// <para>Field Type: Single-Line Text</para>    
          /// <para>Field ID: 714309bb-79c4-4491-a709-cd790d4b59fb</para>
          /// <para>Custom Data: </para>
          /// </summary>
          [SitecoreField(IArticleConstants.TitleFieldName)]
          string Title  {get; set;}
      
        }


  public static partial class IArticleConstants{

      public const string TemplateIdString = "0e7add70-1756-45b7-b0a3-95af072fc68f";
      public static readonly ID TemplateId = new ID(TemplateIdString);
      public const string TemplateName = "Article";

          
      public static readonly ID IntroductionFieldId = new ID("66f51940-5f6f-404b-8dd9-81dee8e6bb07");
      public const string IntroductionFieldName = "Introduction";
      
          
      public static readonly ID Main_ContentFieldId = new ID("07b7ab11-8edf-4edb-a1cc-7c981b2dee04");
      public const string Main_ContentFieldName = "Main Content";
      
          
      public static readonly ID TitleFieldId = new ID("714309bb-79c4-4491-a709-cd790d4b59fb");
      public const string TitleFieldName = "Title";
      
    
  }

  
  /// <summary>
  /// Article
  /// <para></para>
  /// <para>Path: /sitecore/templates/Project/Demo/Page Types/Article</para> 
  /// <para>ID: 0e7add70-1756-45b7-b0a3-95af072fc68f</para>  
  /// </summary>
  [SitecoreType(TemplateId=IArticleConstants.TemplateIdString)] //, Cachable = true
  public partial class Article  : GlassBase, IArticle 
  {
     
            /// <summary>
        /// The Introduction field.
        /// <para></para>
        /// <para>Field Type: Rich Text</para>    
        /// <para>Field ID: 66f51940-5f6f-404b-8dd9-81dee8e6bb07</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
        [SitecoreField(IArticleConstants.IntroductionFieldName)]
        public virtual string Introduction  {get; set;}

            /// <summary>
        /// The Main Content field.
        /// <para></para>
        /// <para>Field Type: Rich Text</para>    
        /// <para>Field ID: 07b7ab11-8edf-4edb-a1cc-7c981b2dee04</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
        [SitecoreField(IArticleConstants.Main_ContentFieldName)]
        public virtual string Main_Content  {get; set;}

            /// <summary>
        /// The Title field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>    
        /// <para>Field ID: 714309bb-79c4-4491-a709-cd790d4b59fb</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
        [SitecoreField(IArticleConstants.TitleFieldName)]
        public virtual string Title  {get; set;}

      }
}
namespace DoctaCore.Project.Demo
{


  /// <summary>
  /// IHome Interface
  /// <para></para>
  /// <para>Path: /sitecore/templates/Project/Demo/Page Types/Home</para> 
  /// <para>ID: 61e89ebd-e65a-4d16-9880-88a88334f882</para>  
  /// </summary>
  [SitecoreType(TemplateId=IHomeConstants.TemplateIdString )] //, Cachable = true
  public partial interface IHome : IGlassBase , global::DoctaCore.Project.Demo.IBase_Page
  {
        }


  public static partial class IHomeConstants{

      public const string TemplateIdString = "61e89ebd-e65a-4d16-9880-88a88334f882";
      public static readonly ID TemplateId = new ID(TemplateIdString);
      public const string TemplateName = "Home";

    
  }

  
  /// <summary>
  /// Home
  /// <para></para>
  /// <para>Path: /sitecore/templates/Project/Demo/Page Types/Home</para> 
  /// <para>ID: 61e89ebd-e65a-4d16-9880-88a88334f882</para>  
  /// </summary>
  [SitecoreType(TemplateId=IHomeConstants.TemplateIdString)] //, Cachable = true
  public partial class Home  : GlassBase, IHome 
  {
     
      }
}
namespace DoctaCore.Project.Demo
{


  /// <summary>
  /// IBase_Page Interface
  /// <para></para>
  /// <para>Path: /sitecore/templates/Project/Demo/Page Types/Base Page</para> 
  /// <para>ID: c14f0635-6f2f-4271-be31-f79276042588</para>  
  /// </summary>
  [SitecoreType(TemplateId=IBase_PageConstants.TemplateIdString )] //, Cachable = true
  public partial interface IBase_Page : IGlassBase 
  {
        }


  public static partial class IBase_PageConstants{

      public const string TemplateIdString = "c14f0635-6f2f-4271-be31-f79276042588";
      public static readonly ID TemplateId = new ID(TemplateIdString);
      public const string TemplateName = "Base Page";

    
  }

  
  /// <summary>
  /// Base_Page
  /// <para></para>
  /// <para>Path: /sitecore/templates/Project/Demo/Page Types/Base Page</para> 
  /// <para>ID: c14f0635-6f2f-4271-be31-f79276042588</para>  
  /// </summary>
  [SitecoreType(TemplateId=IBase_PageConstants.TemplateIdString)] //, Cachable = true
  public partial class Base_Page  : GlassBase, IBase_Page 
  {
     
      }
}
namespace DoctaCore.Project.Demo
{


  /// <summary>
  /// ISite_Root Interface
  /// <para></para>
  /// <para>Path: /sitecore/templates/Project/Demo/Content Types/Site Root</para> 
  /// <para>ID: faf4d312-b07c-404e-89ee-ca43b8c9a015</para>  
  /// </summary>
  [SitecoreType(TemplateId=ISite_RootConstants.TemplateIdString )] //, Cachable = true
  public partial interface ISite_Root : IGlassBase 
  {
        }


  public static partial class ISite_RootConstants{

      public const string TemplateIdString = "faf4d312-b07c-404e-89ee-ca43b8c9a015";
      public static readonly ID TemplateId = new ID(TemplateIdString);
      public const string TemplateName = "Site Root";

    
  }

  
  /// <summary>
  /// Site_Root
  /// <para></para>
  /// <para>Path: /sitecore/templates/Project/Demo/Content Types/Site Root</para> 
  /// <para>ID: faf4d312-b07c-404e-89ee-ca43b8c9a015</para>  
  /// </summary>
  [SitecoreType(TemplateId=ISite_RootConstants.TemplateIdString)] //, Cachable = true
  public partial class Site_Root  : GlassBase, ISite_Root 
  {
     
      }
}
